In [1]:
my_list=[1,2,3,4,5]

In [2]:
import numpy as np

In [3]:
np.array(my_list)

array([1, 2, 3, 4, 5])

In [4]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]

In [5]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [8]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.zeros(2)

array([0., 0.])

In [10]:
np.ones(3)

array([1., 1., 1.])

In [11]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [12]:
np.linspace(0,5)

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [13]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.random.randint(0,50)

26

In [15]:
np.random.rand(10,10)

array([[0.15928924, 0.61372236, 0.98292255, 0.96407874, 0.42104982,
        0.51897564, 0.13189897, 0.2312298 , 0.29085877, 0.0614361 ],
       [0.80268533, 0.07822963, 0.68026812, 0.09081073, 0.64240724,
        0.45360383, 0.88008821, 0.23493872, 0.05331542, 0.92017802],
       [0.98570549, 0.07478537, 0.46644136, 0.40260845, 0.35632291,
        0.85355298, 0.38946411, 0.16752518, 0.87036664, 0.57586641],
       [0.01795605, 0.88634357, 0.97183272, 0.52237267, 0.89573819,
        0.47788997, 0.54130233, 0.73539011, 0.51260834, 0.041495  ],
       [0.86469673, 0.70305752, 0.89468322, 0.17828816, 0.45843765,
        0.06871272, 0.91349467, 0.92213433, 0.79009852, 0.93906761],
       [0.77215912, 0.5844785 , 0.93468702, 0.26388383, 0.23006814,
        0.26494044, 0.17288022, 0.34191247, 0.11584345, 0.63407636],
       [0.70749389, 0.32561534, 0.35047887, 0.2269561 , 0.58116748,
        0.6439872 , 0.15427901, 0.46878718, 0.55409412, 0.05013289],
       [0.57207581, 0.04287359, 0.9343970

In [15]:
np.random.randn(10,100,20)

array([[[ 0.62874943,  2.32311789, -0.98056345, ...,  0.2187896 ,
          0.04776884,  0.48529057],
        [ 0.50897172,  1.75203148,  0.46554014, ..., -0.20647114,
          1.12083103, -1.43691225],
        [-1.32277325, -0.94709453,  0.98462589, ...,  0.22531988,
         -1.39348354,  0.02271807],
        ...,
        [-0.61047383,  0.23647738,  1.3610013 , ...,  1.33214931,
         -0.47016992,  0.6082737 ],
        [ 1.01616114, -0.31215886,  1.0598906 , ..., -1.29434375,
         -0.13036606,  0.40459623],
        [-0.94362009, -1.33745978,  0.38360809, ..., -0.18110215,
         -0.01580972,  0.44345422]],

       [[-1.58042117, -0.58847437,  0.21076824, ..., -0.75849018,
         -0.50281535,  1.49685229],
        [-1.83488801, -1.04815881,  0.10596623, ...,  0.6530982 ,
          0.0526612 ,  0.50836161],
        [-0.44527603,  0.60932166, -0.52748925, ..., -1.60248645,
         -0.8464349 ,  0.16748618],
        ...,
        [-0.37454273, -0.92450848,  0.75794531, ..., -

array attributes

In [17]:
arr = np.arange(25)

In [18]:
ranarr = np.random.randint(0,50,10)

In [19]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [20]:
ranarr

array([24, 20, 23,  5, 13, 32, 38, 16, 22,  3])

In [21]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [27]:
arr.reshape(1,25).shape

(1, 25)

In [29]:
arr.shape

(25,)

In [30]:
ranarr.min()

3

In [31]:
ranarr.argmin()

9

numpy indexing

In [37]:
arr = np.arange(0,11)

In [38]:
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [39]:
arr[7]

7

In [40]:
 arr[1:8]

array([1, 2, 3, 4, 5, 6, 7])

In [41]:
arr[0:5]=100

In [42]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [68]:
slice_of_arr=arr[0:5]

In [69]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [70]:
slice_of_arr[:]=99

In [66]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [71]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [49]:
arr_cpy=arr.copy()

In [50]:
arr_cpy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [72]:
import numpy as np

In [77]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

In [16]:
aarr_nw = np.arange(50).reshape(5,10)

In [17]:
aarr_nw

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [20]:
aarr_nw[2:4,5:7]

array([[25, 26],
       [35, 36]])

In [21]:
ar = np.arange(0,11)

In [22]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
ar + ar

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [24]:
ar * ar

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [25]:
ar / ar

C:\Users\ram14\AppData\Local\Temp\ipykernel_1824\1071685828.py:1: RuntimeWarning: invalid value encountered in divide
  ar / ar


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [26]:
ar % ar

C:\Users\ram14\AppData\Local\Temp\ipykernel_1824\3285001156.py:1: RuntimeWarning: divide by zero encountered in remainder
  ar % ar


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [27]:
np.max(ar)

10

In [28]:
np.exp(ar)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [29]:
np.log(ar)

C:\Users\ram14\AppData\Local\Temp\ipykernel_1824\3877308065.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(ar)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [30]:
ar.argmax()

10

In [31]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [34]:
val = np.ones(10)

In [35]:
val * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [36]:
np.random.randint(0,1)

0